# Generated by Django 5.2.15 on 2026-07-06 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_atual', models.CharField(default='A2/B1 (intermediate-beginner)', max_length=50)),
                ('velocidade_preferida', models.FloatField(default=1.0)),
                ('referencia_nivel', models.TextField(blank=True, default='', help_text="Descrição de conteúdos que o usuário já entende bem, usada como âncora concreta de calibração (ex: 'entende bem podcasts de shadowing como Speak Up Sessions').")),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(choices=[('usuario', 'Usuário'), ('assistente', 'Assistente')], max_length=10)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='conversation.conversa')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddField(
            model_name='conversa',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='conversation.perfil'),
        ),
    ]
